1
SELECT FIRST_NAME|| ' '||LAST_NAME "Menos de 15 años"
, NULL "Entre 15 y 20 años"
, NULL "Mas de 20 años"
FROM EMPLOYEES
WHERE TRUNC(MONTHS_BETWEEN(SYSDATE,HIRE_DATE)/12) < 15

UNION

SELECT NULL "Menos de 15 años"
, FIRST_NAME|| ' '||LAST_NAME "Entre 15 y 20 años"
, NULL "Mas de 20 años"
FROM EMPLOYEES
WHERE TRUNC(MONTHS_BETWEEN(SYSDATE,HIRE_DATE)/12) BETWEEN 15 AND 20

UNION

SELECT NULL "Menos de 15 años"
, NULL "Entre 15 y 20 años"
, FIRST_NAME|| ' '||LAST_NAME "Mas de 20 años"
FROM EMPLOYEES
WHERE TRUNC(MONTHS_BETWEEN(SYSDATE,HIRE_DATE)/12) > 20
;

2
SELECT E.FIRST_NAME|| ' '||E.LAST_NAME "Nombre Completo"
  , L.CITY "Ciudad"
FROM EMPLOYEES E
  INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
  INNER JOIN LOCATIONS L ON D.LOCATION_ID=L.LOCATION_ID
WHERE L.CITY='Seattle'

MINUS

SELECT E.FIRST_NAME|| ' '||E.LAST_NAME "Nombre Completo"
, NULL "Ciudad"
FROM EMPLOYEES E
  INNER JOIN JOBS J ON E.JOB_ID=J.JOB_ID
WHERE J.JOB_TITLE='Purchasing Clerk'
;

3
SELECT FIRST_NAME|| ' '||LAST_NAME
FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'A%'

INTERSECT

SELECT FIRST_NAME|| ' '||LAST_NAME
FROM EMPLOYEES
WHERE JOB_ID LIKE '%MAN';

