1
SELECT D.DEPARTMENT_NAME "Nombre Dpto", COUNT(E.EMPLOYEE_ID) "Nro Empleados"
FROM EMPLOYEES E
    --INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
    INNER JOIN DEPARTMENTS D USING (DEPARTMENT_ID)
GROUP BY D.DEPARTMENT_NAME
ORDER BY 1;

SELECT COUNT(DISTINCT EMPLOYEE_ID) "Nro Empleados"
FROM EMPLOYEES;

SELECT COUNT(DISTINCT DEPARTMENT_ID) "Nro Dptos"
FROM DEPARTMENTS;

2
SELECT COUNT(CASE WHEN COMMISSION_PCT IS NOT NULL THEN EMPLOYEE_ID END)"Nro Empleados con Comision"
    , 100*(MAX(CASE WHEN COMMISSION_PCT IS NOT NULL THEN COMMISSION_PCT END)) ||'%' "Maximo Comision"
    , 100*(MIN(CASE WHEN COMMISSION_PCT IS NOT NULL THEN COMMISSION_PCT END)) ||'%' "Minimo Comision"
    , TO_CHAR(AVG(CASE WHEN COMMISSION_PCT IS NOT NULL THEN COMMISSION_PCT END)*100, 999.999) ||'%' "Comision Media"
FROM EMPLOYEES;