3
-- DEPARTMENT_NAME EMPLEADO MAX(SALARY*(1+NVL(COMMISSION_PCT,0)))
SELECT D.DEPARTMENT_NAME "Nombre Dpto",
       (SELECT E.FIRST_NAME || ' ' || E.LAST_NAME
        FROM EMPLOYEES E
        WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
          AND E.SALARY * (1 + NVL(E.COMMISSION_PCT, 0)) = (
              SELECT MAX(SALARY * (1 + NVL(COMMISSION_PCT, 0)))
              FROM EMPLOYEES
              WHERE DEPARTMENT_ID = D.DEPARTMENT_ID
          )
       ) "Nombre Completo"
FROM DEPARTMENTS D
WHERE D.DEPARTMENT_ID IN (SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES)
ORDER BY 1;