---------------------CREACION DE TABLESPACE----------------------------------------------------------------
CREATE TABLESPACE michi
DATAFILE 'michi.ora'
SIZE 50M
AUTOEXTEND ON
NEXT 10M
MAXSIZE 500M;

------------------------------------ASIGNACION DE TABLESPACE------------------------------------------
ALTER USER VARO
DEFAULT TABLESPACE MICHI
QUOTA 5M ON michi;

--------------------------CREACION DE USUARIOS----------------------------------
CREATE USER CONSULTOR IDENTIFIED BY consultor12345 
DEFAULT TABLESPACE MICHI;
CREATE USER GESTOR IDENTIFIED BY gestor12345 
DEFAULT TABLESPACE MICHI QUOTA 5M ON MICHI;

CONNECT CONSULTOR/consultor12345;

GRANT CONNECT, CREATE SESSION to CONSULTOR, GESTOR;

----------------CREACION DE ROLES----------------------------
CREATE ROLE CONSULTAR_GESTION;
GRANT SELECT on VARO.ARTICULOS TO CONSULTAR_GESTION;
GRANT SELECT ON VARO.CLIENTES TO CONSULTAR_GESTION;
GRANT SELECT ON VARO.VENTAS TO CONSULTAR_GESTION;
GRANT CONSULTAR_GESTION TO CONSULTOR, GESTOR;

DROP ROLE CONSULTAR_GESTION;

CREATE ROLE GESTIONAR_GESTION;
GRANT INSERT, UPDATE, DELETE ON VARO.ARTICULOS TO GESTIONAR_GESTION;
GRANT INSERT, UPDATE, DELETE ON VARO.CLIENTES TO GESTIONAR_GESTION;
GRANT INSERT, UPDATE, DELETE ON VARO.VENTAS TO GESTIONAR_GESTION;
GRANT GESTIONAR_GESTION TO CONSULTOR, GESTOR;

REVOKE CONSULTAR_GESTION FROM GESTOR;

------------------------------MODIFICACION DE CONTRASEÑAS Y ELIMINACION DE PRIVILEGIOS----------------------------------------
ALTER USER GESTOR IDENTIFIED BY GESTOR56789;
DROP USER CONSULTOR CASCADE;

REVOKE CREATE SESSION FROM GESTOR;

---------------------------CREACION DE INDICES----------------------------------
CREATE INDEX CLT_NOM_INDEX ON VARO.CLIENTES(CLT_NOM);

SELECT INDEX_NAME, TABLE_NAME, COLUMN_NAME
FROM USER_IND_COLUMNS
WHERE INDEX_NAME = 'CLT_NOM_INDEX';

---------------MODIFICACION DE CAMPOS
ALTER TABLE VARO.CLIENTES
MODIFY (CLT_POB VARCHAR2(25));

---------------EXPORTACION A CSV-----------------------
SET HEADING OFF;
SET FEEDBACK OFF;
SET COLSEP ",";
SPOOL C:\Users\Mañanas\Downloads\clientes.csv;
SELECT CLT_NUM, CLT_NOM, CLT_POB
FROM VARO.CLIENTES;
SPOOL OFF;
----------------IMPORTACION DESDE CSV-------------------
CREATE OR REPLACE DIRECTORY csv_dir AS '/home/varo/Descargas';
GRANT READ, WRITE ON DIRECTORY csv_dir TO varo;
CREATE TABLE clientes_ext(
    CLT_NUM NUMBER,
    CLT_NOM VARCHAR2(50),
    CLT_POB VARCHAR2(25)
)
ORGANIZATION EXTERNAL (
    TYPE ORACLE_LOADER
    DEFAULT DIRECTORY csv_dir
    ACCESS PARAMETERS (
        RECORDS DELIMITED BY NEWLINE
        FIELDS TERMINATED BY ','
        MISSING FIELD VALUES ARE NULL
        (CLT_NUM, CLT_NOM, CLT_POB)
    )
    LOCATION ('data.csv')
)
REJECT LIMIT UNLIMITED;

INSERT INTO VARO.CLIENTES (clt_num, clt_nom, clt_pob)
SELECT clt_num, clt_nom, clt_pob FROM clientes_ext;

---------------Localizacion del Tablespace----------------
SELECT b.tablespace_name, b.file_name
FROM user_tablespaces a
JOIN user_data_files b
ON a.tablespace_name = b.tablespace_name
WHERE a.tablespace_name = 'MICHI';

SELECT tablespace_name, file_name
FROM dba_data_files
WHERE tablespace_name = 'MICHI';